"""Link the lifter's (UNMODIFIED) oracle_replay.c against the full lifted
module, writing every artifact under output/recomp/oracle/replay/.

Nothing in scripts/recomp/lift/ or output/recomp/lift/ is written to.  The
dispatch table is regenerated here from the module's own lifted_decls.h
rather than by running the lifter's mkdispatch.py, because that writes into
the module directory.
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import shutil
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import peimage  # noqa: E402

ROOT = peimage.REPO_ROOT
OUT = os.path.join(ROOT, "output", "recomp", "oracle")
REPLAY = os.path.join(OUT, "replay")
LIFT_SRC = os.path.join(ROOT, "scripts", "recomp", "lift")
EMCC = os.environ.get(
    "EMCC", os.path.expanduser(r"~/emsdk/upstream/emscripten/emcc"))

TEXT_LO = 0x00401000
TEXT_HI = 0x00B17134


def gen_dispatch(decls_path: str, dst_dir: str) -> int:
    with open(decls_path, encoding="utf8") as fh:
        names = re.findall(r"^void (sub_([0-9a-f]{8}))\(CpuState", fh.read(),
                           re.M)
    allv = sorted((int(h, 16), n) for n, h in set(names))
    entries = [(v, n) for v, n in allv if TEXT_LO <= v < TEXT_HI]
    bogus = [(v, n) for v, n in allv if not (TEXT_LO <= v < TEXT_HI)]
    if bogus:
        # The module declares functions whose VA is nowhere near .text.  They
        # cannot be reached by VA and indexing a direct-mapped table with
        # them reads far out of bounds, so they are dropped here and
        # reported: this is a defect in the lifted module, not in the replay.
        print(f"  WARNING: {len(bogus)} declared functions outside .text "
              f"(dropped): " + ", ".join(f"{v:#010x}" for v, _ in bogus[:12]))
        with open(os.path.join(dst_dir, "bogus_decls.txt"), "w") as bf:
            for v, n in bogus:
                bf.write(f"{v:#010x} {n}\n")
    with open(os.path.join(dst_dir, "dispatch_tbl.h"), "w") as fh:
        fh.write("#ifndef DISPATCH_TBL_H\n#define DISPATCH_TBL_H\n")
        fh.write('#include <stdint.h>\n#include "lifted_decls.h"\n')
        fh.write("typedef void (*recomp_fn)(CpuState *restrict);\n")
        fh.write("#define G_NDISPATCH %du\n" % len(entries))
        fh.write("#define G_TEXT_LO 0x%08xu\n" % TEXT_LO)
        fh.write("#define G_TEXT_HI 0x%08xu\n" % TEXT_HI)
        fh.write("extern const uint32_t g_dva[G_NDISPATCH];\n")
        fh.write("extern const recomp_fn g_dfn[G_NDISPATCH];\n#endif\n")
    with open(os.path.join(dst_dir, "dispatch_tbl.c"), "w") as fh:
        fh.write('/* GENERATED by scripts/recomp/oracle/build_replay.py */\n')
        fh.write('#include "dispatch_tbl.h"\n\n')
        fh.write("const uint32_t g_dva[G_NDISPATCH] = {\n")
        for i in range(0, len(entries), 8):
            fh.write(",".join("0x%08xu" % v for v, _ in entries[i:i + 8]) + ",\n")
        fh.write("};\nconst recomp_fn g_dfn[G_NDISPATCH] = {\n")
        for i in range(0, len(entries), 4):
            fh.write(",".join(n for _, n in entries[i:i + 4]) + ",\n")
        fh.write("};\n")
    return len(entries)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--module-dir",
                    default=os.path.join(ROOT, "output", "recomp", "lift",
                                         "gabs"))
    ap.add_argument("--opt", default="-O1")
    ap.add_argument("--jobs", type=int, default=8)
    a = ap.parse_args()

    os.makedirs(REPLAY, exist_ok=True)
    md = a.module_dir
    for name in ("lifted_decls.h", "recomp_state.h"):
        shutil.copy2(os.path.join(md, name), os.path.join(REPLAY, name))
    shutil.copy2(os.path.join(LIFT_SRC, "recomp_rt.h"),
                 os.path.join(REPLAY, "recomp_rt.h"))
    n = gen_dispatch(os.path.join(REPLAY, "lifted_decls.h"), REPLAY)
    print(f"dispatch table: {n} functions")

    objs = sorted(glob.glob(os.path.join(md, "*.o")))
    print(f"module objects: {len(objs)}")

    t0 = time.time()
    # compile the dispatch table and the lifter's replay driver (read-only
    # source, compiled here rather than in their tree)
    # The module directory already ships its own recomp_rt.o and stubs.o;
    # compiling ours too gives wasm-ld duplicate symbols.
    srcs = [(os.path.join(REPLAY, "dispatch_tbl.c"),
             os.path.join(REPLAY, "dispatch_tbl.o")),
            (os.path.join(LIFT_SRC, "oracle_replay.c"),
             os.path.join(REPLAY, "oracle_replay.o"))]
    for src, dst in srcs:
        cmd = [EMCC, a.opt, "-c", src, "-o", dst,
               "-I", REPLAY, "-I", LIFT_SRC, "-I", md,
               "-Wno-everything"]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"COMPILE FAILED {src}\n{r.stdout}\n{r.stderr}"[:4000])
            return 1
        print(f"  compiled {os.path.basename(src)}")

    out_js = os.path.join(REPLAY, "orc.mjs")
    link = [EMCC, a.opt, "-o", out_js,
            os.path.join(REPLAY, "oracle_replay.o"),
            os.path.join(REPLAY, "dispatch_tbl.o")] + objs + [
        # Host data must live ABOVE every guest region, or writing the PE
        # image at its real VAs tramples emscripten's own static data and the
        # indirect-call table (symptom: "table index is out of bounds" inside
        # orc_load_image).  GLOBAL_BASE is set to the harness's GUEST_HI so
        # the split is exact: < 0x34000000 guest, >= 0x34000000 host.
        "-sGLOBAL_BASE=872415232",
        "-sALLOW_MEMORY_GROWTH=1", "-sINITIAL_MEMORY=1207959552",
        "-sSTACK_SIZE=8388608", "-sEXPORTED_RUNTIME_METHODS=stringToNewUTF8",
        "-sEXPORTED_FUNCTIONS="
        "_orc_load,_orc_run,_orc_nvec,_orc_nfn,_orc_vec_va,"
        "_orc_load_image,_orc_set_strict,_malloc,_free",
        "-sMODULARIZE=1", "-sEXPORT_ES6=1", "-sASSERTIONS=0",
        # fopen() in orc_load/orc_load_image must reach the real
        # filesystem; without NODERAWFS both return -1.
        "-sNODERAWFS=1",
        "-Wno-everything"]
    print("linking ...")
    r = subprocess.run(link, capture_output=True, text=True)
    if r.returncode != 0:
        print(f"LINK FAILED\n{r.stdout}\n{r.stderr}"[:6000])
        return 1
    wasm = os.path.join(REPLAY, "orc.wasm")
    print(f"linked in {time.time()-t0:.0f}s -> {out_js} "
          f"({os.path.getsize(wasm)/1048576:.1f} MB wasm)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
