"""Find real RTTI in the image so __RTDynamicCast can be tested against it.

A dynamic_cast implementation validated against a mock proves only that the
mock matches the implementation. This locates genuine MSVC RTTI descriptor
chains in .rdata -- real vftables, real RTTICompleteObjectLocators, real class
hierarchies -- and emits them as a C header the selftest uses, so the shim is
exercised on the same bytes the game will hand it.

Emits scripts/recomp/host/generated/rtti_cases.h.

Run:  python scripts/recomp/host/rtti_probe.py
"""

import json
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pe import PE, OUT_DIR, hexva  # noqa: E402

GEN = Path(__file__).resolve().parent / "generated"


def main():
    pe = PE()
    GEN.mkdir(parents=True, exist_ok=True)
    rd = pe.section(".rdata")
    lo = pe.image_base + rd.rva
    blob = pe.data[rd.raw_offset:rd.raw_offset + rd.raw_size]

    def r32(va):
        if not (lo <= va < lo + len(blob) - 3):
            v = pe.u32_at_va(va)
            return v if v is not None else 0
        o = va - lo
        return struct.unpack_from("<I", blob, o)[0]

    def cstr(va, n=256):
        s = pe.read_at_va(va, n)
        if not s:
            return ""
        e = s.find(b"\0")
        return s[:e if e >= 0 else n].decode("ascii", "replace")

    cases = []
    # A vftable candidate is a .rdata slot V where V[-1] is a plausible
    # RTTICompleteObjectLocator: signature 0, type descriptor and class
    # hierarchy descriptor both in-image, and the hierarchy self-consistent.
    for off in range(4, len(blob) - 4, 4):
        va = lo + off
        col = struct.unpack_from("<I", blob, off - 4)[0]
        if not pe.is_image_va(col):
            continue
        sig = r32(col + 0x00)
        if sig != 0:
            continue
        td = r32(col + 0x0C)
        chd = r32(col + 0x10)
        if not (pe.is_image_va(td) and pe.is_image_va(chd)):
            continue
        if r32(chd + 0x00) != 0:            # CHD signature
            continue
        nbases = r32(chd + 0x08)
        arr = r32(chd + 0x0C)
        if not (1 <= nbases <= 64 and pe.is_image_va(arr)):
            continue
        name = cstr(td + 8)
        if not name.startswith(".?A"):      # mangled class name
            continue
        # the first entry of the vftable should be code
        first = r32(va)
        if not pe.is_text_va(first):
            continue
        bases = []
        ok = True
        for i in range(nbases):
            bcd = r32(arr + 4 * i)
            if not pe.is_image_va(bcd):
                ok = False
                break
            btd = r32(bcd + 0x00)
            if not pe.is_image_va(btd):
                ok = False
                break
            bname = cstr(btd + 8)
            if not bname.startswith(".?A"):
                ok = False
                break
            bases.append({
                "typeDescriptor": btd, "name": bname,
                "mdisp": struct.unpack("<i", struct.pack("<I", r32(bcd + 0x08)))[0],
                "pdisp": struct.unpack("<i", struct.pack("<I", r32(bcd + 0x0C)))[0],
                "vdisp": struct.unpack("<i", struct.pack("<I", r32(bcd + 0x10)))[0],
            })
        if not ok or len(bases) < 2:
            continue
        cases.append({
            "vftable": va, "col": col, "colOffset": r32(col + 0x04),
            "typeDescriptor": td, "name": name,
            "numBases": nbases, "bases": bases,
        })
        if len(cases) >= 400:
            break

    # Prefer cases with a deep hierarchy and colOffset == 0 (primary base), and
    # with distinct base names, so the walk is genuinely exercised.
    cases.sort(key=lambda c: (-c["numBases"], c["colOffset"]))
    chosen = [c for c in cases if c["colOffset"] == 0][:6]

    with (GEN / "rtti_cases.h").open("w", encoding="utf-8") as fh:
        fh.write("/* GENERATED by scripts/recomp/host/rtti_probe.py.\n"
                 " * Real RTTI descriptor chains from the image, so the\n"
                 " * __RTDynamicCast shim is tested on the bytes the game\n"
                 " * actually hands it rather than on a mock. */\n")
        fh.write("#ifndef RTTI_CASES_H\n#define RTTI_CASES_H\n#include <stdint.h>\n")
        fh.write("typedef struct { uint32_t vftable, typeDescriptor, "
                 "baseTypeDescriptor; int32_t mdisp, pdisp, vdisp;\n"
                 "                 const char *name, *baseName; } RttiCase;\n")
        fh.write("#define G_NRTTI %du\n" % len(chosen))
        fh.write("static const RttiCase g_rtti[%d] = {\n" % max(1, len(chosen)))
        for c in chosen:
            b = c["bases"][1] if len(c["bases"]) > 1 else c["bases"][0]
            fh.write('  {0x%08xu, 0x%08xu, 0x%08xu, %d, %d, %d, "%s", "%s"},\n' % (
                c["vftable"], c["typeDescriptor"], b["typeDescriptor"],
                b["mdisp"], b["pdisp"], b["vdisp"],
                c["name"].replace("\\", "\\\\").replace('"', '\\"'),
                b["name"].replace("\\", "\\\\").replace('"', '\\"')))
        if not chosen:
            fh.write("  {0,0,0,0,0,0,\"\",\"\"},\n")
        fh.write("};\n#endif\n")

    (OUT_DIR / "rtti-cases.json").write_text(
        json.dumps({"candidates": len(cases), "chosen": chosen}, indent=1,
                   default=str), encoding="utf-8")

    print("polymorphic classes with a usable hierarchy: %d" % len(cases))
    print("chosen for the selftest: %d" % len(chosen))
    for c in chosen:
        print("  vftable %s  colOff %-4d  %-42s  %d bases" % (
            hexva(c["vftable"]), c["colOffset"], c["name"][:42], c["numBases"]))
        for b in c["bases"][:4]:
            print("       base %-44s mdisp=%d pdisp=%d vdisp=%d" % (
                b["name"][:44], b["mdisp"], b["pdisp"], b["vdisp"]))
    print()
    print("wrote %s" % (GEN / "rtti_cases.h"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
