"""Generate a SURVEY translation unit: every import returns instead of trapping.

Purpose: answer "what does the boot path demand, in order" in one run,
instead of one relink per blocker.

Each generated shim
  * logs the symbol and its guest call site the first time it is reached,
  * performs the callee's own return using the host's MEASURED arg_bytes
    (`ret 0` for cdecl, `ret N` for stdcall), so the guest stack stays
    synchronised,
  * returns EAX = 0.

Only the SEMANTICS are faked. That is still a lie, so the output is a
survey and nothing more: after the first faked return the guest's state
is not trustworthy and any later blocker may be a consequence rather than
a cause. The ORDER in which imports are first demanded is real evidence,
and that is what this is for.

Indices are parsed out of the host's own generated shim_weak.c so the
survey and the host agree on which isaac_imports[] entry each symbol is.
"""

import argparse
import os
import re


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host-weak",
                    default="scripts/recomp/host/generated/shim_weak.c")
    ap.add_argument("--out", required=True)
    ap.add_argument("--host-src", default="scripts/recomp/host/src",
                    help="directory of hand-written host shims. Any imp_* "
                         "defined STRONGLY there is a real implementation and "
                         "must not be overridden by the survey -- doing so is "
                         "a hard duplicate-symbol link error, which is the "
                         "correct behaviour and how this was caught.")
    args = ap.parse_args()

    src = open(args.host_weak, encoding="utf8").read()
    pairs = re.findall(
        r"void (imp_\w+)\(CpuState \*restrict cpu\) \{\s*"
        r"static const isaac_import \*self;\s*"
        r"if \(!self\) self = &isaac_imports\[(\d+)\];", src)
    if not pairs:
        raise SystemExit("no imp_*/index pairs found in %s" % args.host_weak)

    strong = set()
    for fn in sorted(os.listdir(args.host_src)):
        if not fn.endswith(".c"):
            continue
        txt = open(os.path.join(args.host_src, fn), encoding="utf8").read()
        for m in re.finditer(r"(?m)^void (imp_\w+)\s*\(", txt):
            strong.add(m.group(1))
    kept = [(n, i) for n, i in pairs if n not in strong]
    print("host implements %d strongly; survey covers %d of %d"
          % (len(strong), len(kept), len(pairs)))
    pairs = kept

    with open(args.out, "w") as fh:
        fh.write('/* GENERATED by mksurvey.py -- SURVEY BUILD ONLY.\n'
                 ' * Strong overrides that RETURN instead of trapping, so one\n'
                 ' * run reports every import the boot path demands and the\n'
                 ' * order it demands them in.  Semantics are faked; the stack\n'
                 ' * discipline is not (arg_bytes comes from the host table).\n'
                 ' * Never ship this TU. */\n')
        fh.write('#include "isaac_host.h"\n#include <stdio.h>\n\n')
        fh.write('''static unsigned g_seq;

void isaac_survey_hit(const isaac_import *imp, CpuState *restrict cpu) {
  static unsigned char seen[4096];
  unsigned idx = (unsigned)(imp - isaac_imports);
  uint32_t site = isaac_retaddr(cpu);
  if (idx < sizeof(seen) && !seen[idx]) {
    seen[idx] = 1;
    printf("  [%3u] %-46s ret 0x%08x  %s  args=%u  sites=%u\\n",
           ++g_seq, imp->symbol, site,
           imp->is_stdcall ? "stdcall" : "cdecl  ",
           (unsigned)imp->arg_bytes, imp->call_sites);
    fflush(stdout);
  }
  /* the callee's own epilogue: pop return address, then purge args */
  cpu->EIP = isaac_r32(cpu->ESP);
  cpu->ESP += 4u + (imp->is_stdcall ? imp->arg_bytes : 0u);
  cpu->EAX = 0;
}

unsigned isaac_survey_count(void) { return g_seq; }

''')
        for name, idx in pairs:
            fh.write('void %s(CpuState *restrict cpu) '
                     '{ isaac_survey_hit(&isaac_imports[%s], cpu); }\n'
                     % (name, idx))

    print("survey shims: %d -> %s" % (len(pairs), args.out))


if __name__ == "__main__":
    main()
